language: php

php:
- 7.2

before_install:
- composer global require hirak/prestissimo

install:
- composer self-update
- composer install

script:
- bin/sync

notifications:
 email:
 - info@redaxmedia.com